# Generated by Django 3.1.3 on 2020-11-10 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20201110_0942'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
            ],
        ),
        migrations.RemoveField(
            model_name='movie',
            name='title',
        ),
        migrations.AddField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_score',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies.Genre'),
        ),
    ]
